// Arrays de mensajes preventivos y colores
const mensajes = [
    "Nunca compartas tus fotos privadas con personas que no conoces.",
    "Si alguien te pide guardar un secreto incómodo en internet, cuéntaselo a un adulto de confianza.",
    "Bloquea y reporta a cualquier persona que insista en hablar de temas íntimos.",
    "Recuerda: tu seguridad vale más que cualquier amistad en línea.",
    "Nunca aceptes reunirte en persona con alguien que solo conoces de internet.",
    "No aceptes solicitudes de amistad de desconocidos.",
    "No compartas tu dirección ni tu colegio en redes sociales.",
    "Si un adulto quiere hablarte en privado, cuéntaselo a tus padres o tutores.",
    "No confíes en personas que conoces solo en línea.",
    "Nunca accedas a videollamadas con desconocidos.",
    "No envíes fotos tuyas con uniforme escolar.",
    "Usa contraseñas seguras y no las compartas.",
    "Configura la privacidad de tus redes sociales.",
    "Bloquea y reporta a usuarios sospechosos.",
    "Si te sientes incómodo, detén la conversación de inmediato.",
    "No compartas tu número de teléfono con extraños.",
    "No aceptes regalos virtuales de desconocidos.",
    "Nunca creas que alguien que acabas de conocer en internet es tu 'mejor amigo'.",
    "Si alguien insiste demasiado en hablar contigo, cuéntalo a un adulto.",
    "No compartas tu ubicación en tiempo real.",
    "Evita hablar de temas íntimos por chat.",
    "Si un desconocido te hace sentir raro, sigue tu instinto y aléjate.",
    "Mantén tus perfiles en redes sociales como privados.",
    "No publiques información sobre tu rutina diaria.",
    "Si alguien te pide dinero o favores, no accedas y repórtalo.",
    "No compartas contraseñas ni códigos de verificación.",
    "Desconfía de personas que quieren conocerte demasiado rápido.",
    "Si recibes mensajes inapropiados, no respondas y repórtalos.",
    "No te sientas obligado a responder mensajes de desconocidos.",
    "Aprende a utilizar las herramientas de bloqueo y reporte.",
    "Comparte tus experiencias en línea con adultos de confianza.",
    "No te dejes presionar para hacer cosas que no quieres.",
    "Tu bienestar emocional es más importante que cualquier relación virtual.",
    "Si algo te parece sospechoso, probablemente lo sea.",
    "No subestimes los riesgos en internet.",
    "Educa a tus amigos sobre los peligros del grooming.",
    "Participa en talleres y charlas sobre seguridad digital.",
    "Confía en tu intuición cuando algo no te parezca bien.",
    "No cedas ante el chantaje emocional.",
    "Recuerda que en internet no todos son quienes dicen ser.",
    "Mantén una comunicación abierta con tus padres sobre tu actividad en línea.",
    "Establece límites claros en tus interacciones digitales.",
    "No compartas imágenes que puedan ser usadas en tu contra.",
    "Aprende a reconocer las señales de grooming.",
    "Si eres víctima de acoso, busca ayuda inmediatamente.",
    "No normalices comportamientos inapropiados en línea.",
    "Tu privacidad es tu derecho, defiéndela.",
    "Sé consciente de que lo que publicas en internet puede permanecer para siempre.",
    "Utiliza seudónimos en lugar de tu nombre real cuando sea posible.",
    "No te sientas culpable si eres víctima de grooming, busca ayuda."
];

// Colores cálidos pastel para cada mensaje
const coloresCalidos = [
    { header: '#FFB6C1', primary: '#FFA7B3', secondary: '#FFD1DC', nombre: 'Rosa pastel' },
    { header: '#FFDAC1', primary: '#FFCBA7', secondary: '#FFE5B4', nombre: 'Melocotón pastel' },
    { header: '#E2F0CB', primary: '#D4E8B1', secondary: '#F0F8C6', nombre: 'Verde menta pastel' },
    { header: '#B5EAD7', primary: '#A3E1C9', secondary: '#D4F1E6', nombre: 'Verde agua pastel' },
    { header: '#C7CEEA', primary: '#B5C0EB', secondary: '#D9DFF5', nombre: 'Azul lavanda pastel' },
    { header: '#FFD1DC', primary: '#FFC2D1', secondary: '#FFE4EC', nombre: 'Rosa claro pastel' },
    { header: '#FFE5B4', primary: '#FFD899', secondary: '#FFF0D4', nombre: 'Melón pastel' },
    { header: '#D8BFD8', primary: '#C9A9C9', secondary: '#E8D4E8', nombre: 'Ciruela pastel' },
    { header: '#B0E0E6', primary: '#9BD4DB', secondary: '#D1F0F4', nombre: 'Azul polvo pastel' },
    { header: '#F0E68C', primary: '#E6D87C', secondary: '#F8F4C8', nombre: 'Amarillo caqui pastel' },
    { header: '#98FB98', primary: '#89F089', secondary: '#C8FAC8', nombre: 'Verde pálido pastel' },
    { header: '#DDA0DD', primary: '#D18FD1', secondary: '#EBC0EB', nombre: 'Ciruela pastel' },
    { header: '#87CEFA', primary: '#78BFEA', secondary: '#C2E5FF', nombre: 'Azul cielo pastel' },
    { header: '#FFA07A', primary: '#FF9164', secondary: '#FFD1C2', nombre: 'Salmón claro pastel' },
    { header: '#20B2AA', primary: '#1BA39B', secondary: '#8BD9D4', nombre: 'Verde mar claro pastel' },
    { header: '#778899', primary: '#6A7A8A', secondary: '#B8C2CC', nombre: 'Gris pizarra claro pastel' },
    { header: '#BDB76B', primary: '#AEA85B', secondary: '#E0DCB4', nombre: 'Oliva oscuro pastel' },
    { header: '#FF69B4', primary: '#F05AA3', secondary: '#FFB8DB', nombre: 'Rosa fuerte pastel' },
    { header: '#CD5C5C', primary: '#BE4D4D', secondary: '#E8A8A8', nombre: 'Rojo indio pastel' },
    { header: '#F08080', primary: '#E17171', secondary: '#F8C8C8', nombre: 'Rojo claro pastel' },
    { header: '#9370DB', primary: '#8461CB', secondary: '#C9B8F0', nombre: 'Púrpura medio pastel' },
    { header: '#3CB371', primary: '#2DA461', secondary: '#96E0B4', nombre: 'Verde mar medio pastel' },
    { header: '#FFA500', primary: '#F09600', secondary: '#FFD699', nombre: 'Naranja pastel' },
    { header: '#DA70D6', primary: '#CB61C6', secondary: '#EDB8EA', nombre: 'Orquídea pastel' },
    { header: '#6495ED', primary: '#5586E6', secondary: '#B3CEF5', nombre: 'Azul aciano pastel' },
    { header: '#DC143C', primary: '#CD0535', secondary: '#F08A9D', nombre: 'Carmesí pastel' },
    { header: '#00CED1', primary: '#00BFC2', secondary: '#80E7E8', nombre: 'Turquesa pastel' },
    { header: '#FF4500', primary: '#F03600', secondary: '#FFA280', nombre: 'Rojo naranja pastel' },
    { header: '#6A5ACD', primary: '#5B4BBE', secondary: '#B5ADE6', nombre: 'Azul pizarra pastel' },
    { header: '#FF1493', primary: '#F00585', secondary: '#FF8ACA', nombre: 'Rosa profundo pastel' },
    { header: '#1E90FF', primary: '#0F81F0', secondary: '#8FC8FF', nombre: 'Azul esquivador pastel' },
    { header: '#B22222', primary: '#A31313', secondary: '#D99191', nombre: 'Rojo fuego pastel' },
    { header: '#FFD700', primary: '#F0C800', secondary: '#FFEB80', nombre: 'Oro pastel' },
    { header: '#ADFF2F', primary: '#9EF01A', secondary: '#D6FF97', nombre: 'Verde chartreuse pastel' },
    { header: '#FF00FF', primary: '#F000F0', secondary: '#FF80FF', nombre: 'Magenta pastel' },
    { header: '#40E0D0', primary: '#31D1C1', secondary: '#A0F0E8', nombre: 'Turquesa medio pastel' },
    { header: '#EE82EE', primary: '#DF73DF', secondary: '#F6C1F6', nombre: 'Violeta pastel' },
    { header: '#F5DEB3', primary: '#E6CFA4', secondary: '#FAEFD9', nombre: 'Trigo pastel' },
    { header: '#00FF7F', primary: '#00F071', secondary: '#80FFBF', nombre: 'Verde primavera pastel' },
    { header: '#D2691E', primary: '#C35A0F', secondary: '#E9B48F', nombre: 'Chocolate pastel' },
    { header: '#7FFF00', primary: '#70F000', secondary: '#BFFF80', nombre: 'Verde chartreuse pastel' },
    { header: '#8A2BE2', primary: '#7B1CD3', secondary: '#C595F1', nombre: 'Azul violeta pastel' },
    { header: '#A52A2A', primary: '#961B1B', secondary: '#D29595', nombre: 'Marrón pastel' },
    { header: '#DEB887', primary: '#CFA978', secondary: '#EFDCC3', nombre: 'Madera pastel' },
    { header: '#5F9EA0', primary: '#508F91', secondary: '#AFCFD0', nombre: 'Azul cadete pastel' },
    { header: '#7CFC00', primary: '#6DED00', secondary: '#BEFE80', nombre: 'Verde hierba pastel' },
    { header: '#D2B48C', primary: '#C3A57D', secondary: '#E9DAC6', nombre: 'Bronceado pastel' },
    { header: '#DAA520', primary: '#CB9612', secondary: '#EDD290', nombre: 'Dorado pastel' },
    { header: '#FF7F50', primary: '#F07042', secondary: '#FFBFA0', nombre: 'Coral pastel' },
    { header: '#6495ED', primary: '#5586E6', secondary: '#B3CEF5', nombre: 'Azul aciano pastel' }
];

// Palabras clave para análisis de respuestas del usuario
const palabrasClave = {
    peligrosas: [
        "sí", "si", "claro", "ok", "okay", "dale", "bueno", "vale", "por qué no",
        "está bien", "de acuerdo", "perfecto", "genial", "me encanta", "me gusta",
        "quiero", "me interesa", "cuenta conmigo", "confío", "te creo", "eres genial"
    ],
    seguras: [
        "no", "nunca", "jamás", "bloquear", "reportar", "adulto", "padres", "mamá", "papá",
        "tutor", "profesor", "director", "policía", "denunciar", "peligroso", "sospechoso",
        "incómodo", "no me gusta", "basta", "para", "detente", "aléjate", "no quiero",
        "me incómoda", "me molesta", "es inapropiado", "no es normal"
    ],
    neutrales: [
        "quién eres", "qué quieres", "por qué", "cómo", "cuándo", "dónde",
        "no entiendo", "no sé", "quizás", "tal vez", "veremos", "pensaré",
        "no estoy seguro", "tal vez", "no conozco", "no te creo"
    ]
};